# Generated by Django 3.2.8 on 2021-10-26 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('created', models.DateTimeField(blank=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(blank=True, verbose_name='Modificado em')),
                ('submitter_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('status', models.IntegerField(choices=[(1, 'Aberto'), (2, 'Re-Aberto'), (5, 'Duplicado'), (6, 'Análisar Ticket'), (14, 'Análise de Riscos'), (7, 'Criar Ação'), (8, 'Implementar Ação'), (9, 'Verificar Ação'), (10, 'Análisar Eficácia'), (11, 'Comunicar Interessados'), (12, 'Análise Crítica'), (3, 'Resolvido'), (4, 'Encerrado'), (13, 'Registrado')], default=1, verbose_name='Status')),
                ('on_hold', models.BooleanField(blank=True, default=False, verbose_name='Em Espera')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('resolution', models.TextField(blank=True, null=True, verbose_name='Resolução')),
                ('priority', models.IntegerField(blank=3, choices=[(1, '1. Crítico'), (2, '2. Alto'), (3, '3. Normal'), (4, '4. Baixo'), (5, '5. Muito Baixo')], default=3, help_text='1 = Máxima Prioridade, 5 = Mínima Prioridade', verbose_name='Prioridade')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='Prazo de Entrega')),
                ('last_escalation', models.DateTimeField(blank=True, editable=False, null=True)),
                ('secret_key', models.CharField(default=uuid.uuid4, max_length=36, verbose_name='Chave de acesso')),
                ('is_finished', models.BooleanField(default=False, verbose_name='Encerrado')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_to', to=settings.AUTH_USER_MODEL, verbose_name='Atribuído Para')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ('id',),
                'get_latest_by': 'created',
            },
        ),
    ]
