# Generated by Django 3.2.8 on 2021-11-04 16:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('0', 'PENDENTE'), ('1', 'FEITO FORA DO PRAZO'), ('2', 'FEITO DENTRO DO PRAZO'), ('3', 'CANCELADO')], max_length=30, null=True, verbose_name='Status')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='Prazo')),
                ('comments', models.CharField(blank=True, max_length=1500, null=True, verbose_name='Comentários/Observações')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('url', models.URLField(blank=True, max_length=255, null=True, verbose_name='Url externo')),
                ('id_google_event', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID Google Agenda')),
                ('secret_key', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, verbose_name='Chave secreta para ver/editar eventos por usuários sem login')),
                ('executed_at', models.DateTimeField(blank=True, null=True, verbose_name='Feito em')),
            ],
        ),
    ]
